version: "3.8"
services:
    site:
        build:
            context: .
            dockerfile: Dockerfile
        working_dir: /home/node/app
        command: "bash -c 'npm run start:prod'"
        init: true
        security_opt:
            - seccomp=assets/chrome.json
        ports:
            - "3000:3000/tcp"
