name: test
on:
  - push
jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: bahmutov/npm-install@v1
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: bahmutov/npm-install@v1
      - run: npm run test
        env:
          CI: true