name: test
on:
  - push
jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 15.4
      - run: npm ci
      - uses: actions/upload-artifact@v2
        with:
          path: node_modules
  compile:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: npm run build
  test:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - run: npm run test
        env:
          CI: true